### DISCUSSION TITLE
Stormcrawler-docker and OpenSearch

### DISCUSSION THREAD

**Discussion by annikajohannimloh** [DigitalPebble/storm-crawler#1078] [Q&A] [answered]
Hi all,
I am brand new to the topic of search engines, crawlers and docker. My goal is to implement a search engine with OpenSearch. I saw your talk at OpenSearch from February this year, so I decided to use Stormcrawler.
In the docker-compose.yml it says how I want to run elasticSearch instead of URLFrontier. How exactly does this work with OpenSearch? I have seen that there is a crawler frontier for OpenSearch which is based on URLFrontier (https://github.com/PresearchOfficial/opensearch-frontier).
I wanted to ask you, as experts, how I manage to combine these two things. I am grateful for any tip :)

**Comment by jnioche** [comment, marked as answer]
Hi I have just realised that the stormcrawler-docker had no discussions section, I have created one. Your question would be better there but I'll start answering here for now.

the purpose of the stormcrawler-docker setup is mostly to show to run the Storm services in Docker. Understanding how Storm runs is a difficulty for new users and the stormcrawler-docker resources try to help with that.

> I want to run elasticSearch instead of URLFrontier. How exactly does this work with OpenSearch? 

 Of course when it comes to StormCrawler, you are not limited to a particular backend, you can use Elasticsearch, SOLR, OpenSearch or URLFrontier. You don't need more than one. In your case, you can remove the sections about URLFrontier, ElasticSearch, Kibana and just add service definitions for OpenSearch.

>  I have seen that there is a crawler frontier for OpenSearch which is based on URLFrontier

This is the implementation of the URLFrontier service running on Opensearch. This would be used **instead** of using the spouts and statusupdater bolts from the Opensearch module in SC. It won't help you with indexing the documents into OpenSearch or storing metrics.

It is probably easier to start with the Opensearch module instead of URLFrontier. 

One you have the services running in Docker (the Storm ones + OpenSearch), have a look at [the opensearch module](https://github.com/DigitalPebble/storm-crawler/tree/master/external/opensearch) to see how to use the Maven archetype.

Of course you don't have to use Docker and could install OpenSearch and Apache Storm on your computer. 

I hope this helps

**Reply by annikajohannimloh** [reply]
Thank you for the answer. I got OpenSearch and Stormcrawler running in docker. 
The service definitions of opensearch look like this:

```
  frontier:
    image: opensearchproject/opensearch:latest
    container_name: frontier
    environment:
      - cluster.name=frontier-cluster
      - node.name=frontier-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - plugins.security.disabled=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - "127.0.0.1:7071:7071"
```


After that I followed the steps in the readme file from https://github.com/DigitalPebble/storm-crawler/tree/master/external/opensearch
When importing the dashboard I get the following error message:

<img width="962" alt="Bildschirm­foto 2023-06-19 um 13 48 43" src="https://github.com/DigitalPebble/storm-crawler/assets/59923877/63711076-a39c-4937-b3b4-dd2484effab1">

Can you help me with this? Maybe I have overlooked a step.

**Reply by annikajohannimloh** [reply]
I also ran the steps of the configured README file from the newly created project. After installing Apache Storm for this and creating a seeds.txt, I get the following error message when running from the topology: 

<img width="1014" alt="Bildschirm­foto 2023-06-19 um 17 57 40" src="https://github.com/DigitalPebble/storm-crawler/assets/59923877/bf6ad127-3fa2-4e56-ba8a-eeb2db0209e5">

**Reply by jnioche** [reply]
about the authentication issue, did you add Dashboards into docker compose or only OpenSearch?
The port mapping for OpenSearch doesn't look correct, should be something like 
```
    ports:
      - 9200:9200 # REST API
```

for the second problem, it looks like you need to have python installed

**Reply by annikajohannimloh** [reply]
In fact, I had only added OpenSearch to the docker-compose. So I changed the port and added Dashboard in addition. 

What I don't quite understand is that I previously had OpenSearch and Stormcrawler running in Docker at the same time. With the port changes and adding OpenSearch and Dashboard to Stormcrawler docker-compose, I can no longer run OpenSearch in parallel with stormcrawler. I.e. that the OpenSearch component now runs on top of stormcrawler (If you can say so)? 

I also installed python and added it to PATH. I was able to start the crawl tpoplogy in local mode as a result. In the README file it says that you can also start the topology with `storm jar`. What exactly is the difference between the two and what should a command for this look like? 
At this point I do not get further with my current knowledge unfortunately. 
What are the next steps, i.e. to be able to make a search query more concretely to individualize it?

I apologize for the many questions, but I am very interested in the subject and willing to understand this. :)

**Reply by jnioche** [reply]
you need to have the port changes reflected in the configuration, look in opensearch-conf.yaml

Maybe if you haven't done so already, look at the tutorials on https://www.youtube.com/playlist?list=PLiqxzwp5B4ZnvBEsdTwSHVJ5FRDTlCl9V

They are about Elasticsearch and probably about an older version of SC but they should help you understand some of the concepts a bit better.

The one I gave at the OpenSearch community meeting in Feb should also be useful https://www.youtube.com/watch?v=azHYI9pnjos&list=PLzgr9zSpws15dkg6979WeKkLg4T-vLNeW&index=2

**Reply by annikajohannimloh** [reply]
> you need to have the port changes reflected in the configuration, look in opensearch-conf.yaml

I don't understand what you mean by that. The yaml file has the same port for OpenSearch as I use in the docker-compose. I can call both the dashboard and the storm ui, but I can't reach frontier via port 9200 (same behavior when I start OpenSearch in docker only). 

> Maybe if you haven't done so already, look at the tutorials on https://www.youtube.com/playlist?list=PLiqxzwp5B4ZnvBEsdTwSHVJ5FRDTlCl9V

I looked into the tutorial and learned that you can use the storm ui by using the `storm jar` command. I ran the following command: `storm jar target/crawler-1.0-SNAPSHOT.jar org.apache.storm.flux.Flux --remote crawler.flux`

However, I get the following error message: 
<img width="1463" alt="Bildschirm­foto 2023-06-22 um 17 47 17" src="https://github.com/DigitalPebble/storm-crawler/assets/59923877/6f047ca2-c09e-44f0-9998-025022e5e6c9">

I installed Zookeeper manually and changed the following 
```
########### These MUST be filled in for a storm configuration
storm.zookeeper.servers:
  - "localhost"
storm.local.dir: "/Users/annika/apache-storm-2.4.0/data"
nimbus.seeds: ["localhost"]
supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703
```
 in storm.yaml. Unfortunately, the error message does not go away.

**Reply by jnioche** [reply]
> I don't understand what you mean by that. The yaml file has the same port for OpenSearch as I use in the docker-compose. 

Good

isn't zookeeper already running with docker-compose? you shouldn't have to run it separately. Maybe try `docker ps` to check that it starts alongside the Storm services. 
You shouldn't have to modify storm.yaml. Since the Storm services run as containers, 'localhost' is not going to point to the right server

**Reply by annikajohannimloh** [reply]
Okay, thanks. 
I misunderstood about Zookeeper, it is of course started via docker.

<img width="1486" alt="Bildschirm­foto 2023-06-24 um 17 40 09" src="https://github.com/DigitalPebble/storm-crawler/assets/59923877/80e68c9b-b0ae-46bc-a6ab-a1f734bac855">

I have undone the changes to the storm.yaml. However, I still can't execute the command without errors. In my Storm ui are under nimbus summary two entries. The leader is found in the meantime, but I get a java.net.UnknownHostException. Normally "nimbus" should be the leader, which is then also found or?

![Bildschirm­foto 2023-06-24 um 17 50 44](https://github.com/DigitalPebble/storm-crawler/assets/59923877/daf8ea17-1559-4405-af10-179314dd3fb4)

<img width="1472" alt="Bildschirm­foto 2023-06-24 um 17 49 57" src="https://github.com/DigitalPebble/storm-crawler/assets/59923877/570528c3-2e3c-4ea6-a53a-ebfe2dcb1650">

**Reply by jnioche** [reply]
I am a bit puzzled because it works fine when I use the docker-compose file. Have you made any progress since or are you still stuck?

**Reply by annikajohannimloh** [reply]
No, unfortunately not. I have actually only followed the steps from the readme files.

**Reply by annikajohannimloh** [reply]
So I rebooted everything again and started from scratch. 
But already at the first call of the storm Ui are under the nimbus summary 2 entries (See above)

**Reply by rzo1** [reply]
Maybe add your whole setup as is into a separate GitHub repo, so we get an idea.

**Reply by jnioche** [reply]
Don't have the setup running here but if I remember correctly the UI does show 2 entries, one not being active but this is not a problem

**Reply by annikajohannimloh** [reply]
I put my code in a private repo and invited you two to join

**Reply by rzo1** [reply]
You can add `hostname: nimbus` to the `nimbus` container, so the cryptic container hostname will be replaced with `nimbus`. 

To connect from a topology deployed inside of docker, you need to adjust `localhost` to the appropriate container / hostname, so docker is able to connect to the related instance(s).

With the initial setup (and the hostname change) from your repo,  going to localhost:5601 reveals:

```bash
OpenSearch Dashboards server is not ready yet
```
Bad thing, next step -> check the logs:

```bash
{"type":"log","@timestamp":"2023-06-29T11:22:56Z","tags":["error","savedobjects-service"],"pid":1,"message":"This version of OpenSearch Dashboards (v2.8.0) is incompatible with the following OpenSearch nodes in your cluster: v2.7.0 @ 172.20.0.3:9200 (172.20.0.3)"}
````
Version incompatibility. Let's fix: I would suggest to use `2.7.0` instead of `latest` to avoid such issues.

With downgraded versions (`2.7.0`) for both, we finally get http://0.0.0.0:5601/app/home#/ up and running.

Next, we import the dashboards:

```bash
rzo1@node-147:~/IdeaProjects/bla/nfc21crawler/dashboards$ ./importDashboards.sh 
Importing status dashboard into OpenSearch Dashboards
{"successCount":4,"success":true,"successResults":[{"type":"index-pattern","id":"7445c390-7339-11e9-9289-ffa3ee6775e4","meta":{"title":"status","icon":"indexPatternApp"}},{"type":"visualization","id":"status-count","meta":{"title":"status count","icon":"visualizeApp"}},{"type":"visualization","id":"Top-Hosts","meta":{"title":"Top Hosts","icon":"visualizeApp"}},{"type":"dashboard","id":"Crawl-status","meta":{"title":"Crawl status","icon":"dashboardApp"}}]}
Importing metrics dashboard into OpenSearch Dashboards
{"successCount":9,"success":true,"successResults":[{"type":"index-pattern","id":"b5c3bbd0-7337-11e9-9289-ffa3ee6775e4","meta":{"title":"metrics","icon":"indexPatternApp"}},{"type":"visualization","id":"Fetcher-:-#-active-threads","meta":{"title":"Fetcher : # active threads","icon":"visualizeApp"}},{"type":"visualization","id":"Fetcher-:-num-queues","meta":{"title":"Fetcher : num queues","icon":"visualizeApp"}},{"type":"visualization","id":"Fetcher-:-pages-fetched","meta":{"title":"Fetcher : pages fetched","icon":"visualizeApp"}},{"type":"visualization","id":"Fetcher-:-URLs-waiting-in-queues","meta":{"title":"Fetcher : URLs waiting in queues","icon":"visualizeApp"}},{"type":"visualization","id":"Fetcher-:-average-bytes-per-second","meta":{"title":"Fetcher : average bytes per second","icon":"visualizeApp"}},{"type":"visualization","id":"Fetcher-:-average-pages-per-second","meta":{"title":"Fetcher : average pages per second","icon":"visualizeApp"}},{"type":"visualization","id":"Total-bytes-fetched","meta":{"title":"Total bytes fetched","icon":"visualizeApp"}},{"type":"dashboard","id":"Crawl-metrics","meta":{"title":"Crawl metrics","icon":"dashboardApp"}}]}

```

Next step: We need to replace `localhost` in the `opensearch-conf.yaml` by the actual hostname inside the docker network which is `opensearch-frontier`.

So, no we need to create the index definition via `OS_IndexInit.sh` from the storm crawler main project inside opensearch module (it might fail, so you need to rename `indexer.mapping` into `content.mapping`. @jnioche We might want to fix that?

```bash
./OS_IndexInit.sh 
Deleted 'status' index, now recreating it...
{"acknowledged":true,"shards_acknowledged":true,"index":"status"}
Deleted 'content' index, now recreating it...
{"acknowledged":true,"shards_acknowledged":true,"index":"content"}
Deleted 'metrics' index, now recreating it...
{"acknowledged":true}

```

Note: Might be a bit puzzling based on local OS, etc.

So far so good... let's do the rest. I normally put everything relevant into a single folder, e.g. `deploy` or something:

```
rzo1@node-147:~/IdeaProjects/bla/deploy$ ls -lah
insgesamt 119M
-rw-rw-r-- 1 zowallar zowallar 4,0K Jun 29 13:18 crawler-conf.yaml
-rw-rw-r-- 1 zowallar zowallar 3,6K Jun 29 13:18 crawler.flux
-rw-rw-r-- 1 zowallar zowallar  814 Jun 29 13:57 injector.flux
-rw-rw-r-- 1 zowallar zowallar 119M Jun 29 13:42 nfc21crawler-1.0-SNAPSHOT.jar
-rw-rw-r-- 1 zowallar zowallar 3,1K Jun 29 13:34 opensearch-conf.yaml
-rw-rw-r-- 1 zowallar zowallar   17 Jun 29 13:18 seeds.txt
```

I normally use a custom `flux` config to inject seeds before going remote:

```bash
name: "injector"

includes:
    - resource: true
      file: "/crawler-default.yaml"
      override: false

    - resource: false
      file: "crawler-conf.yaml"
      override: true

    - resource: false
      file: "opensearch-conf.yaml"
      override: true

spouts:
  - id: "spout"
    className: "com.digitalpebble.stormcrawler.spout.FileSpout"
    parallelism: 1
    constructorArgs:
      - "."
      - "seeds.txt"
      - true

bolts:
  - id: "status"
    className: "com.digitalpebble.stormcrawler.opensearch.persistence.StatusUpdaterBolt"
    parallelism: 1

streams:
  - from: "spout"
    to: "status"
    grouping:
      type: CUSTOM
      customClass:
        className: "com.digitalpebble.stormcrawler.util.URLStreamGrouping"
        constructorArgs:
          - "byHost"
      streamId: "status"
```

My default docker network is called `bla_default`, so for me it would be something like 

```bash

docker run --network bla_default -it \
--rm \
-v "$(pwd)/seeds.txt:/apache-storm-2.4.0/seeds.txt" \
-v "$(pwd)/crawler-conf.yaml:/apache-storm-2.4.0/crawler-conf.yaml" \
-v "$(pwd)/opensearch-conf.yaml:/apache-storm-2.4.0/opensearch-conf.yaml" \
-v "$(pwd)/injector.flux:/apache-storm-2.4.0/injector.flux" \
-v "$(pwd)/nfc21crawler-1.0-SNAPSHOT.jar:/apache-storm-2.4.0/nfc21crawler-1.0-SNAPSHOT.jar" \
storm:2.4-temurin \
storm local nfc21crawler-1.0-SNAPSHOT.jar org.apache.storm.flux.Flux injector.flux --local-ttl 3600
```

After a short amount of time (based on the amount of seeds), I usually going to manually terminate it.
We can check the progress of the seed injection by looking into the OS dashboard after creating related index patterns.
It will show something like

```bash
url:http://somu-url.de/ status:DISCOVERED key:somu-url.de nextFetchDate:Jun 29, 2023 @ 14:01:34.000 _id:8fa31cf33fb567c56cdf4d43871a986a60fc17dd98582a2219fc79209cf97caf _type: - _index:status _score: -
```

Next, we can go full deployment mode:

```bash
docker run --network bla_default -it \
--rm \
-v "$(pwd)/seeds.txt:/apache-storm-2.4.0/seeds.txt" \
-v "$(pwd)/crawler-conf.yaml:/apache-storm-2.4.0/crawler-conf.yaml" \
-v "$(pwd)/opensearch-conf.yaml:/apache-storm-2.4.0/opensearch-conf.yaml" \
-v "$(pwd)/crawler.flux:/apache-storm-2.4.0/crawler.flux" \
-v "$(pwd)/nfc21crawler-1.0-SNAPSHOT.jar:/apache-storm-2.4.0/nfc21crawler-1.0-SNAPSHOT.jar" \
storm:2.4-temurin \
storm jar nfc21crawler-1.0-SNAPSHOT.jar org.apache.storm.flux.Flux --remote crawler.flux

```

Note: I encountered some issues inside Docker with the TIKA bolts, so I removed them from the flux config (as I didn't have time atm to dig into it

I changed `crawler.flux` to: 

```yaml
name: "crawler"

includes:
    - resource: true
      file: "/crawler-default.yaml"
      override: false

    - resource: false
      file: "crawler-conf.yaml"
      override: true

    - resource: false
      file: "opensearch-conf.yaml"
      override: true

spouts:
  - id: "spout"
    className: "com.digitalpebble.stormcrawler.opensearch.persistence.AggregationSpout"
    parallelism: 10

bolts:
  - id: "filter"
    className: "com.digitalpebble.stormcrawler.bolt.URLFilterBolt"
    parallelism: 1
  - id: "partitioner"
    className: "com.digitalpebble.stormcrawler.bolt.URLPartitionerBolt"
    parallelism: 1
  - id: "fetcher"
    className: "com.digitalpebble.stormcrawler.bolt.FetcherBolt"
    parallelism: 1
  - id: "sitemap"
    className: "com.digitalpebble.stormcrawler.bolt.SiteMapParserBolt"
    parallelism: 1
  - id: "parse"
    className: "com.digitalpebble.stormcrawler.bolt.JSoupParserBolt"
    parallelism: 1
  - id: "index"
    className: "com.digitalpebble.stormcrawler.opensearch.bolt.IndexerBolt"
    parallelism: 1
  - id: "status"
    className: "com.digitalpebble.stormcrawler.opensearch.persistence.StatusUpdaterBolt"
    parallelism: 1
  - id: "deleter"
    className: "com.digitalpebble.stormcrawler.opensearch.bolt.DeletionBolt"
    parallelism: 1
  - id: "status_metrics"
    className: "com.digitalpebble.stormcrawler.opensearch.metrics.StatusMetricsBolt"
    parallelism: 1

streams:
  - from: "spout"
    to: "partitioner"
    grouping:
      type: SHUFFLE

  - from: "spout"
    to: "status_metrics"
    grouping:
      type: SHUFFLE

  - from: "partitioner"
    to: "fetcher"
    grouping:
      type: FIELDS
      args: ["key"]

  - from: "fetcher"
    to: "sitemap"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - from: "sitemap"
    to: "parse"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - from: "parse"
    to: "index"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - from: "fetcher"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "sitemap"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "parse"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "index"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"


```

and the urls started to flow in ;-)

Hope it helps.
