### DISCUSSION TITLE
Increase crawling speed of the crawler.

### DISCUSSION THREAD

**Discussion by msghasan** [DigitalPebble/storm-crawler#1080] [Q&A]
HI Julien,

We are trying to speed up our crawling speed. Currently our crawling lack and the speed is around 1.5 urls per second and I want to increase it to 9 urls persec.

I have deployed storm crawler over kubernetes and using a node pool of 4 nodes of 3.92 cores each and memory of 29.72 gb each.

I am running 8 replicas supervisors with 1 worker in each supervisor

We are using selenium grid for crawling and running 100 chrome replicas over kubernetes.

We are using storm-crawler 2.7 and apache storm version 2.4

I need help to achieve the above mentioned speed. 

Can you guide me into the direction how can I achieve this I will upload all the config documents required for you to analyse. 

crawler-conf.yaml
```
config:
  topology.workers: 8
  topology.message.timeout.secs: 300
  topology.max.spout.pending: 500
  topology.debug: false

  fetcher.threads.number: 20
  fetcher.threads.per.queue: 1
  fetcher.server.delay: 1
  fetcher.server.delay.force: true
  fetcher.metrics.time.bucket.secs: 10
 

  kf.bootstrap.servers: localhost:9092
  kf.auto.offset.reset: earliest
  kf.consumer.seedurl.topic: SeedUrlsTopic
  kf.producer.urlstatus.topic: UrlStatus
  kf.producer.htmlsource.topic: HtmlSource


  topology.worker.childopts: "-Djava.net.preferIPv4Stack=true"


  topology.kryo.register:
    - com.digitalpebble.stormcrawler.Metadata
    - java.util.LinkedList
    - com.digitalpebble.stormcrawler.persistence.Status
    - java.util.concurrent.atomic.AtomicLong
    - org.apache.storm.generated.NodeInfo

  metadata.transfer:
    - projectId
    - seedUrlId

  metadata.persist:
    - _redirTo
    - error.cause
    - error.source
    - isSitemap
    - isFeed
    - fetch.statusCode
    - fetch.byteLength
    - fetch.loadingTime
    - fetch.timeInQueues
    - fetch.exception


  http.robots.file.skip: true


  http.robots.headers.skip: true


  http.robots.meta.skip: true

  http.agent.name: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
  http.agent.version: "2.0"
  http.agent.description: "Chrome Browser"
  http.agent.url: "https://test.com"
  http.agent.email: "test@test.com"

  http.content.limit: 262144
  http.protocol.implementation: "codes.util.SeleniumGridImpl"
  https.protocol.implementation: "codes.util.SeleniumGridImpl"
  partition.url.mode: "byDomain"

  selenium.grid.address: http://localhost:4444/wd/hub

  selenium.capabilities.browserName: chrome


  redirections.allowed: true
  parser.emitOutlinks: false

  parsefilters.config.file: "parsefilters.json"
  urlfilters.config.file: "urlfilters.json"

  fetchInterval.default: -1

  fetchInterval.fetch.error: 600


  fetchInterval.error: 600


  max.fetch.errors: 3


  status.updater.use.cache: false


  textextractor.include.pattern:
    - DIV[id="maincontent"]
    - DIV[itemprop="articleBody"]
    - ARTICLE

  textextractor.exclude.tags:
    - STYLE
    - SCRIPT


  indexer.url.fieldname: "url"
  indexer.text.fieldname: "content"
  indexer.canonical.name: "canonical"
  indexer.md.mapping:
    - parse.title=title
    - parse.keywords=keywords
    - parse.description=description
    - domain=domain

  
  topology.metrics.consumer.register:
    - class: "org.apache.storm.metric.LoggingMetricsConsumer"
      parallelism.hint: 1
      argument: "yyyy-MM-dd"

  fetcher.max.crawl.delay.force: true
  http.trust.everything: true
```
  storm.yaml
 ```
 storm.zookeeper.servers:
      - "zookeeper-crawler-entrypoint.$NAMESPACE.svc.cluster.local"
    nimbus.seeds: ["nimbus-crawler-entrypoint.$NAMESPACE.svc.cluster.local"]

    supervisor.slots.ports:
      - 6700
    
    logviewer.port: 80
    storm.zookeeper.port: 2181

    worker.heap.memory.mb: 12083
    supervisor.memory.capacity.mb: 120832
    topology.worker.max.heap.size.mb: 12083

    topology.component.resources.onheap.memory.mb: 572
    worker.childopts: "-Xmx%HEAP-MEM%m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"
```
   
es-conf.yaml
```
config:
  
  es.indexer.addresses: "localhost"
  es.indexer.index.name: "content"

  es.indexer.create: false
  es.indexer.bulkActions: 100
  es.indexer.flushInterval: "2s"
  es.indexer.concurrentRequests: 1


  es.metrics.addresses: "http://localhost:9200"
  es.metrics.index.name: "metrics"


  es.html.address: "localhost"


  es.status.address: "localhost"
  es.status.addresses: "http://localhost:9200"
  es.status.index.name: "status"



  es.status.routing: true
  es.status.routing.fieldname: "key"
  es.status.bulkActions: 500
  es.status.flushInterval: "5s"
  es.status.concurrentRequests: 1
  spout.ttl.purgatory: 60


  spout.min.delay.queries: 2000

  spout.reset.fetchdate.after: 120

  es.status.max.buckets: 10
  es.status.max.urls.per.bucket: 4

  es.status.bucket.field: "metadata.projectId"

  es.status.bucket.sort.field:
    - "nextFetchDate"
    - "url"

  es.status.global.sort.field: "nextFetchDate"


  es.status.max.start.offset: 500


  es.status.sample: false


  es.status.query.timeout: -1

  es.status.recentDate.increase: -1
  es.status.recentDate.min.gap: -1
  topology.metrics.consumer.register:
    - class: "com.digitalpebble.stormcrawler.elasticsearch.metrics.MetricsConsumer"
      parallelism.hint: 1
 ```

topology.yaml
```
name: "crawler"

includes:
  - resource: true
    file: "/crawler-default.yaml"
    override: false

  - resource: false
    file: "crawler-conf.yaml"
    override: true

  - resource: false
    file: "es-conf.yaml"
    override: true

  - resource: false
    file: "mongo-conf.yaml"
    override: true

  - resource: false
    file: "minio-conf.yaml"
    override: true

spouts:
  - id: "spout"
    className: "com.digitalpebble.stormcrawler.elasticsearch.persistence.AggregationSpout"
    parallelism: 10
  - id: "kafka-spout"
    className: "codes.kafka.client.AddSeedUrlsSpout"
    parallelism: 1

bolts:
  - id: "filter"
    className: "com.digitalpebble.stormcrawler.bolt.URLFilterBolt"
    parallelism: 1
  - id: "partitioner"
    className: "com.digitalpebble.stormcrawler.bolt.URLPartitionerBolt"
    parallelism: 1
  - id: "fetcher"
    className: "codes.bolt.CustomFetcherBolt"
    parallelism: 80
  - id: "sitemap"
    className: "digitalpebble.stormcrawler.bolt.SiteMapParserBolt"
    parallelism: 1
  - id: "parse"
    className: "codes.bolt.CustomJSoupParserBolt"
    parallelism: 3
  - id: "status"
    className: "codes.bolt.CustomStatusUpdaterBolt"
    parallelism: 8
  - id: "status_metrics"
    className: "com.digitalpebble.stormcrawler.elasticsearch.metrics.StatusMetricsBolt"
    parallelism: 1
  - id: "extract_html"
    className: "codes.extract.html.ExtractHtmlBolt"
    parallelism: 4
  - id: "smart_filter"
    className: "codes.filter.SmartFilterBolt"
    parallelism: 1
  - id: "es_index"
    className: "codes.elasticsearch.persistence.ESIndexerBolt"
    parallelism: 1

streams:
  - from: "spout"
    to: "partitioner"
    grouping:
      type: SHUFFLE

  - from: "spout"
    to: "status_metrics"
    grouping:
      type: SHUFFLE

  - from: "kafka-spout"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "partitioner"
    to: "fetcher"
    grouping:
      type: FIELDS
      args: ["key"]

  - from: "fetcher"
    to: "sitemap"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - from: "fetcher"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "sitemap"
    to: "parse"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - from: "parse"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "parse"
    to: "extract_html"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "extract_html"

  - from: "parse"
    to: "smart_filter"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "smart_filter"

  - from: "smart_filter"
    to: "es_index"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "index_filter"

  - from: "smart_filter"
    to: "status"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "status"

  - from: "extract_html"
    to: "es_index"
    grouping:
      type: FIELDS
      args: ["url"]
      streamId: "index_html"
```
