### ISSUE TITLE
storm-crawler-solr bug. Missing DeletionBolt bolt code.

### ISSUE THREAD

**Issue by syefimov** [DigitalPebble/storm-crawler#1050]
[ ] Bug
storm-crawler-solr 2.9-shapshot
com.digitalpebble.stormcrawler.solr.persistence.StatusUpdaterBolt

StatusUpdaterBolt extends AbstractStatusUpdaterBolt. AbstractStatusUpdaterBolt has a call
```
 if (status == Status.ERROR) {
            _collector.emit(Constants.DELETION_STREAM_NAME, new Values(url, metadata));
}
```
Solution: DeletionBolt.java is attached. Update defaulr crawler.flux

```
  - id: "deleter"
    className: "com.digitalpebble.stormcrawler.solr.bolt.DeletionBolt"
    parallelism: 1

..

  - from: "status"
    to: "deleter"
    grouping:
      type: LOCAL_OR_SHUFFLE
      streamId: "deletion"
```
[DeletionBolt.txt](https://github.com/DigitalPebble/storm-crawler/files/11163091/DeletionBolt.txt)
