### ISSUE TITLE
Add test coverage reports with JaCoCo

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#1075]
and export to [Coveralls](https://coveralls.io/github/DigitalPebble/storm-crawler)

We know that the test coverage is far from perfect, especially for the bolts but knowing where it can be improved would be good.

**Comment by jnioche** [comment]
The github actions should also be configured -> https://github.com/marketplace/actions/coveralls-github-action

**Comment by jnioche** [comment]
Note to self

`mvn clean test jacoco:report coveralls:report -DrepoToken=xxxxxxx
`

**Comment by jnioche** [comment]
> The github actions should also be configured -> https://github.com/marketplace/actions/coveralls-github-action

@rzo1 you are the expert, any chance you could have a look at it? ;-) The matrix makes things a bit more complicated
the repo token is already stored as a secret in github

**Comment by rzo1** [comment]
@jnioche I would leave the matix build as is and just add another workflow to compute coverage for master only.

Something like

```yaml
name: Code Coverage

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Coveralls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Build & test with Maven and coverage
        run: mvn clean test jacoco:report
      - name: Post to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: jacoco
```

wdyt?
