### ISSUE TITLE
Refactor configuration of timeouts in Selenium protocol

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#1101]
The configuration of the timeouts is quite error prone.  

[The default values are set to 0
](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/resources/crawler-default.yaml#L174)
```
  selenium.implicitlyWait: 0
  selenium.pageLoadTimeout: 0
  selenium.scriptTimeout: 0
```
If not set explicitly in the configuration, the default value of 0 is used which leads to a script timeout. 

Instead we should it at -1 in the default config so that it is visible for illustration purposes and modify the code so that it is only set if the value is >=0. This would in effect mean: rely on Selenium's default unless specified otherwise, which feels a lot cleaner. It also adds an additional safety as negative values are not accepted.

We will also change the config to use a map, feels a bit cleaner conceptually

```
  # rely on selenium's default values
  # set to a value >= 0 to override
  selenium.timeouts:
    script: -1
    pageLoad: -1
    implicit: -1
```
