### ISSUE TITLE
User agent substitution not handled correctly

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#1109]
The mechanism for setting the user agent in the Selenium conf is not working properly. It currently expects it to be in a string but in practice it is:

1. within a list
2. that list is within a map

```
  selenium.capabilities:
    browserName: "chrome"
    goog:chromeOptions:
       args:
         - "--disable-dev-shm-usage"
         - "--no-sandbox"
         - "--user-agent=$useragent"
 ```
 
 It is never a simple value at the top level
