### ISSUE TITLE
ES - settings done via configuration 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#376]
We should be able to configure the settings for a given ES connection via the config e.g.

```yaml
  es.status.settings:
    cluster.name: "elasticsearch"
    request.headers.X-Found-Cluster: "blablabla"
    action.bulk.compress: "false"
    shield.transport.ssl: "false"
```
including the cluster name. This would be useful for connecting to a Shield-enabled cluster.
