### ISSUE TITLE
Custom schedule based on metadata for non-success pages

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#386]
#283 adds a custom schedule triggered by metadata for all successfully fetched pages. It is not applied to non-success fetches (redirects and errors). However, in certain cases (see commoncrawl/news-crawl#14) it's desirable to have a custom fetch schedule which is takes both metadata and status into account.

**Comment by jnioche** [comment]
Good idea. We could perhaps have the status in the param name e.g.

`fetchInterval.FETCH_ERROR.isFeed=true: 10`

or change to a structured object instead which would be a tad cleaner

```
custom.fetchInterval:
       metadata.key: "isFeed"
       metadata.value: "true"
       status: "FETCHED"
       value: 10       
```

@sebastian-nagel what do you think?
