### ISSUE TITLE
Harmonise param names for SQL

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#619]
Most config keys are prefixed with "mysql." instead we should use "sql" and make the code as implementation neutral as possible.
Would be good to make the configuration of the connection entirely via the conf file and not hardcoded

**Comment by jnioche** [comment]
This is a first step towards making the SQL module 'implementation neutral' where possible.

**Comment by jnioche** [comment]
The configuration of the connection is now done like this

```
  sql.connection:
   url: "jdbc:mysql://localhost:3306/crawl"
   user: "myuser"
   password: "mypassword"
   rewriteBatchedStatements: "true"
   useBatchMultiSend: "true"
```
and is implementation neutral. You can pass key / values specific to the SQL backend used.
