### ISSUE TITLE
MetricsConsumer takes an optional date format 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#724]
We don't need 3 classes to implement two flavours of time formatted index names when the MetricsConsumer can be configured with an optional argument like

```
    topology.metrics.consumer.register:
         - class: "com.digitalpebble.stormcrawler.elasticsearch.metrics.MetricsConsumer"
           parallelism.hint: 1
           argument: "yyyy-MM-dd"
```

which is more flexible and economical
